name: Release

on:
  push:
    tags: [ v* ]
    
jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 10
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select Xcode 12.0.1"
        uses: devbotsxyz/xcode-select@master
        with:
          version: 12.0

      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-name: sadmac
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Build & Archive"
        uses: devbotsxyz/xcode-archive@master

      - name: "Import Certificate: Distribution"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-name: sadmac
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Export & Sign Release Build"
        uses: devbotsxyz/xcode-export-archive@master


#      - name: Release app
#        uses: softprops/action-gh-release@v1
#        with:
#          files: build/${{ env.PRODUCT_MODULE_NAME }}-${{ env.MARKETING_VERSION }}.zip
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
